import { Fragment } from "react";
import { Popover, Transition } from "@headlessui/react";
import {
  AcademicCapIcon,
  AdjustmentsIcon,
  AnnotationIcon,
  ArchiveIcon,
  ArrowCircleDownIcon,
  ArrowCircleLeftIcon,
  ArrowCircleRightIcon,
  ArrowCircleUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowNarrowDownIcon,
  ArrowNarrowLeftIcon,
  ArrowNarrowRightIcon,
  ArrowNarrowUpIcon,
  ArrowRightIcon,
  ArrowSmDownIcon,
  ArrowSmLeftIcon,
  ArrowSmRightIcon,
  ArrowSmUpIcon,
  ArrowUpIcon,
  ArrowsExpandIcon,
  AtSymbolIcon,
  BackspaceIcon,
  BadgeCheckIcon,
  BanIcon,
  BeakerIcon,
  BellIcon,
  BookOpenIcon,
  BookmarkAltIcon,
  BookmarkIcon,
  BriefcaseIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarIcon,
  CameraIcon,
  CashIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChartSquareBarIcon,
  ChatAlt2Icon,
  ChatAltIcon,
  ChatIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDoubleDownIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDoubleUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChipIcon,
  ClipboardCheckIcon,
  ClipboardCopyIcon,
  ClipboardIcon,
  ClipboardListIcon,
  ClockIcon,
  CloudDownloadIcon,
  CloudIcon,
  CloudUploadIcon,
  CodeIcon,
  CogIcon,
  CollectionIcon,
  ColorSwatchIcon,
  CreditCardIcon,
  CubeIcon,
  CubeTransparentIcon,
  CurrencyBangladeshiIcon,
  CurrencyDollarIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyRupeeIcon,
  CurrencyYenIcon,
  CursorClickIcon,
  DatabaseIcon,
  DesktopComputerIcon,
  DeviceMobileIcon,
  DeviceTabletIcon,
  DocumentAddIcon,
  DocumentDownloadIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  DocumentRemoveIcon,
  DocumentReportIcon,
  DocumentSearchIcon,
  DocumentTextIcon,
  DotsCircleHorizontalIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DownloadIcon,
  DuplicateIcon,
  EmojiHappyIcon,
  EmojiSadIcon,
  ExclamationCircleIcon,
  ExclamationIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FastForwardIcon,
  FilmIcon,
  FilterIcon,
  FingerPrintIcon,
  FireIcon,
  FlagIcon,
  FolderAddIcon,
  FolderDownloadIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderRemoveIcon,
  GiftIcon,
  GlobeAltIcon,
  GlobeIcon,
  HandIcon,
  HashtagIcon,
  HeartIcon,
  HomeIcon,
  IdentificationIcon,
  InboxIcon,
  InboxInIcon,
  InformationCircleIcon,
  KeyIcon,
  LibraryIcon,
  LightBulbIcon,
  LightningBoltIcon,
  LinkIcon,
  LocationMarkerIcon,
  LockClosedIcon,
  LockOpenIcon,
  LoginIcon,
  LogoutIcon,
  MailIcon,
  MailOpenIcon,
  MapIcon,
  MenuAlt1Icon,
  MenuAlt2Icon,
  MenuAlt3Icon,
  MenuAlt4Icon,
  MenuIcon,
  MicrophoneIcon,
  MinusCircleIcon,
  MinusIcon,
  MinusSmIcon,
  MoonIcon,
  MusicNoteIcon,
  NewspaperIcon,
  OfficeBuildingIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PauseIcon,
  PencilAltIcon,
  PencilIcon,
  PhoneIcon,
  PhoneIncomingIcon,
  PhoneMissedCallIcon,
  PhoneOutgoingIcon,
  PhotographIcon,
  PlayIcon,
  PlusCircleIcon,
  PlusIcon,
  PlusSmIcon,
  PresentationChartBarIcon,
  PresentationChartLineIcon,
  PrinterIcon,
  PuzzleIcon,
  QrcodeIcon,
  QuestionMarkCircleIcon,
  ReceiptRefundIcon,
  ReceiptTaxIcon,
  RefreshIcon,
  ReplyIcon,
  RewindIcon,
  RssIcon,
  SaveAsIcon,
  SaveIcon,
  ScaleIcon,
  ScissorsIcon,
  SearchCircleIcon,
  SearchIcon,
  SelectorIcon,
  ServerIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SparklesIcon,
  SpeakerphoneIcon,
  StarIcon,
  StatusOfflineIcon,
  StatusOnlineIcon,
  StopIcon,
  SunIcon,
  SupportIcon,
  SwitchHorizontalIcon,
  SwitchVerticalIcon,
  TableIcon,
  TagIcon,
  TemplateIcon,
  TerminalIcon,
  ThumbDownIcon,
  ThumbUpIcon,
  TicketIcon,
  TranslateIcon,
  TrashIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  TruckIcon,
  UploadIcon,
  UserAddIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserRemoveIcon,
  UsersIcon,
  VariableIcon,
  VideoCameraIcon,
  ViewBoardsIcon,
  ViewGridAddIcon,
  ViewGridIcon,
  ViewListIcon,
  VolumeOffIcon,
  VolumeUpIcon,
  WifiIcon,
  XCircleIcon,
  XIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "@heroicons/react/outline";
import React, { useState } from "react";
import "react-toastify/dist/ReactToastify.css";

const icons = [
  { id: 1, name: "AcademicCapIcon", icon: AcademicCapIcon },
  { id: 2, name: "AdjustmentsIcon", icon: AdjustmentsIcon },
  { id: 3, name: "AnnotationIcon", icon: AnnotationIcon },
  { id: 4, name: "ArchiveIcon", icon: ArchiveIcon },
  { id: 5, name: "ArrowCircleDownIcon", icon: ArrowCircleDownIcon },
  { id: 6, name: "ArrowCircleLeftIcon", icon: ArrowCircleLeftIcon },
  { id: 7, name: "ArrowCircleRightIcon", icon: ArrowCircleRightIcon },
  { id: 8, name: "ArrowCircleUpIcon", icon: ArrowCircleUpIcon },
  { id: 9, name: "ArrowDownIcon", icon: ArrowDownIcon },
  { id: 10, name: "ArrowLeftIcon", icon: ArrowLeftIcon },
  { id: 11, name: "ArrowNarrowDownIcon", icon: ArrowNarrowDownIcon },
  { id: 12, name: "ArrowNarrowLeftIcon", icon: ArrowNarrowLeftIcon },
  { id: 13, name: "ArrowNarrowRightIcon", icon: ArrowNarrowRightIcon },
  { id: 14, name: "ArrowNarrowUpIcon", icon: ArrowNarrowUpIcon },
  { id: 15, name: "ArrowRightIcon", icon: ArrowRightIcon },
  { id: 16, name: "ArrowSmDownIcon", icon: ArrowSmDownIcon },
  { id: 17, name: "ArrowSmLeftIcon", icon: ArrowSmLeftIcon },
  { id: 18, name: "ArrowSmRightIcon", icon: ArrowSmRightIcon },
  { id: 19, name: "ArrowSmUpIcon", icon: ArrowSmUpIcon },
  { id: 20, name: "ArrowUpIcon", icon: ArrowUpIcon },
  { id: 21, name: "ArrowsExpandIcon", icon: ArrowsExpandIcon },
  { id: 22, name: "AtSymbolIcon", icon: AtSymbolIcon },
  { id: 23, name: "BackspaceIcon", icon: BackspaceIcon },
  { id: 24, name: "BadgeCheckIcon", icon: BadgeCheckIcon },
  { id: 25, name: "BanIcon", icon: BanIcon },
  { id: 26, name: "BeakerIcon", icon: BeakerIcon },
  { id: 27, name: "BellIcon", icon: BellIcon },
  { id: 28, name: "BookOpenIcon", icon: BookOpenIcon },
  { id: 29, name: "BookmarkAltIcon", icon: BookmarkAltIcon },
  { id: 30, name: "BookmarkIcon", icon: BookmarkIcon },
  { id: 31, name: "BriefcaseIcon", icon: BriefcaseIcon },
  { id: 32, name: "CakeIcon", icon: CakeIcon },
  { id: 33, name: "CalculatorIcon", icon: CalculatorIcon },
  { id: 34, name: "CalendarIcon", icon: CalendarIcon },
  { id: 35, name: "CameraIcon", icon: CameraIcon },
  { id: 36, name: "CashIcon", icon: CashIcon },
  { id: 37, name: "ChartBarIcon", icon: ChartBarIcon },
  { id: 38, name: "ChartPieIcon", icon: ChartPieIcon },
  { id: 39, name: "ChartSquareBarIcon", icon: ChartSquareBarIcon },
  { id: 40, name: "ChatAlt2Icon", icon: ChatAlt2Icon },
  { id: 41, name: "ChatAltIcon", icon: ChatAltIcon },
  { id: 42, name: "ChatIcon", icon: ChatIcon },
  { id: 43, name: "CheckCircleIcon", icon: CheckCircleIcon },
  { id: 44, name: "CheckIcon", icon: CheckIcon },
  { id: 45, name: "ChevronDoubleDownIcon", icon: ChevronDoubleDownIcon },
  { id: 46, name: "ChevronDoubleLeftIcon", icon: ChevronDoubleLeftIcon },
  { id: 47, name: "ChevronDoubleRightIcon", icon: ChevronDoubleRightIcon },
  { id: 48, name: "ChevronDoubleUpIcon", icon: ChevronDoubleUpIcon },
  { id: 49, name: "ChevronDownIcon", icon: ChevronDownIcon },
  { id: 50, name: "ChevronLeftIcon", icon: ChevronLeftIcon },
  { id: 51, name: "ChevronRightIcon", icon: ChevronRightIcon },
  { id: 52, name: "ChevronUpIcon", icon: ChevronUpIcon },
  { id: 53, name: "ChipIcon", icon: ChipIcon },
  { id: 54, name: "ClipboardCheckIcon", icon: ClipboardCheckIcon },
  { id: 55, name: "ClipboardCopyIcon", icon: ClipboardCopyIcon },
  { id: 56, name: "ClipboardIcon", icon: ClipboardIcon },
  { id: 57, name: "ClipboardListIcon", icon: ClipboardListIcon },
  { id: 58, name: "ClockIcon", icon: ClockIcon },
  { id: 59, name: "CloudDownloadIcon", icon: CloudDownloadIcon },
  { id: 60, name: "CloudIcon", icon: CloudIcon },
  { id: 61, name: "CloudUploadIcon", icon: CloudUploadIcon },
  { id: 62, name: "CodeIcon", icon: CodeIcon },
  { id: 63, name: "CogIcon", icon: CogIcon },
  { id: 64, name: "CollectionIcon", icon: CollectionIcon },
  { id: 65, name: "ColorSwatchIcon", icon: ColorSwatchIcon },
  { id: 66, name: "CreditCardIcon", icon: CreditCardIcon },
  { id: 67, name: "CubeIcon", icon: CubeIcon },
  { id: 68, name: "CubeTransparentIcon", icon: CubeTransparentIcon },
  { id: 69, name: "CurrencyBangladeshiIcon", icon: CurrencyBangladeshiIcon },
  { id: 70, name: "CurrencyDollarIcon", icon: CurrencyDollarIcon },
  { id: 71, name: "CurrencyEuroIcon", icon: CurrencyEuroIcon },
  { id: 72, name: "CurrencyPoundIcon", icon: CurrencyPoundIcon },
  { id: 73, name: "CurrencyRupeeIcon", icon: CurrencyRupeeIcon },
  { id: 74, name: "CurrencyYenIcon", icon: CurrencyYenIcon },
  { id: 75, name: "CursorClickIcon", icon: CursorClickIcon },
  { id: 76, name: "DatabaseIcon", icon: DatabaseIcon },
  { id: 77, name: "DesktopComputerIcon", icon: DesktopComputerIcon },
  { id: 78, name: "DeviceMobileIcon", icon: DeviceMobileIcon },
  { id: 79, name: "DeviceTabletIcon", icon: DeviceTabletIcon },
  { id: 80, name: "DocumentAddIcon", icon: DocumentAddIcon },
  { id: 81, name: "DocumentDownloadIcon", icon: DocumentDownloadIcon },
  { id: 82, name: "DocumentDuplicateIcon", icon: DocumentDuplicateIcon },
  { id: 83, name: "DocumentIcon", icon: DocumentIcon },
  { id: 84, name: "DocumentRemoveIcon", icon: DocumentRemoveIcon },
  { id: 85, name: "DocumentReportIcon", icon: DocumentReportIcon },
  { id: 86, name: "DocumentSearchIcon", icon: DocumentSearchIcon },
  { id: 87, name: "DocumentTextIcon", icon: DocumentTextIcon },
  { id: 88, name: "DotsCircleHorizontalIcon", icon: DotsCircleHorizontalIcon },
  { id: 89, name: "DotsHorizontalIcon", icon: DotsHorizontalIcon },
  { id: 90, name: "DotsVerticalIcon", icon: DotsVerticalIcon },
  { id: 91, name: "DownloadIcon", icon: DownloadIcon },
  { id: 92, name: "DuplicateIcon", icon: DuplicateIcon },
  { id: 93, name: "EmojiHappyIcon", icon: EmojiHappyIcon },
  { id: 94, name: "EmojiSadIcon", icon: EmojiSadIcon },
  { id: 95, name: "ExclamationCircleIcon", icon: ExclamationCircleIcon },
  { id: 96, name: "ExclamationIcon", icon: ExclamationIcon },
  { id: 97, name: "ExternalLinkIcon", icon: ExternalLinkIcon },
  { id: 98, name: "EyeIcon", icon: EyeIcon },
  { id: 99, name: "EyeOffIcon", icon: EyeOffIcon },
  { id: 100, name: "FastForwardIcon", icon: FastForwardIcon },
  { id: 101, name: "FilmIcon", icon: FilmIcon },
  { id: 102, name: "FilterIcon", icon: FilterIcon },
  { id: 103, name: "FingerPrintIcon", icon: FingerPrintIcon },
  { id: 104, name: "FireIcon", icon: FireIcon },
  { id: 105, name: "FlagIcon", icon: FlagIcon },
  { id: 106, name: "FolderAddIcon", icon: FolderAddIcon },
  { id: 107, name: "FolderDownloadIcon", icon: FolderDownloadIcon },
  { id: 108, name: "FolderIcon", icon: FolderIcon },
  { id: 109, name: "FolderOpenIcon", icon: FolderOpenIcon },
  { id: 110, name: "FolderRemoveIcon", icon: FolderRemoveIcon },
  { id: 111, name: "GiftIcon", icon: GiftIcon },
  { id: 112, name: "GlobeAltIcon", icon: GlobeAltIcon },
  { id: 113, name: "GlobeIcon", icon: GlobeIcon },
  { id: 114, name: "HandIcon", icon: HandIcon },
  { id: 115, name: "HashtagIcon", icon: HashtagIcon },
  { id: 116, name: "HeartIcon", icon: HeartIcon },
  { id: 117, name: "HomeIcon", icon: HomeIcon },
  { id: 118, name: "IdentificationIcon", icon: IdentificationIcon },
  { id: 119, name: "InboxIcon", icon: InboxIcon },
  { id: 120, name: "InboxInIcon", icon: InboxInIcon },
  { id: 121, name: "InformationCircleIcon", icon: InformationCircleIcon },
  { id: 122, name: "KeyIcon", icon: KeyIcon },
  { id: 123, name: "LibraryIcon", icon: LibraryIcon },
  { id: 124, name: "LightBulbIcon", icon: LightBulbIcon },
  { id: 125, name: "LightningBoltIcon", icon: LightningBoltIcon },
  { id: 126, name: "LinkIcon", icon: LinkIcon },
  { id: 127, name: "LocationMarkerIcon", icon: LocationMarkerIcon },
  { id: 128, name: "LockClosedIcon", icon: LockClosedIcon },
  { id: 129, name: "LockOpenIcon", icon: LockOpenIcon },
  { id: 130, name: "LoginIcon", icon: LoginIcon },
  { id: 131, name: "LogoutIcon", icon: LogoutIcon },
  { id: 132, name: "MailIcon", icon: MailIcon },
  { id: 133, name: "MailOpenIcon", icon: MailOpenIcon },
  { id: 134, name: "MapIcon", icon: MapIcon },
  { id: 135, name: "MenuAlt1Icon", icon: MenuAlt1Icon },
  { id: 136, name: "MenuAlt2Icon", icon: MenuAlt2Icon },
  { id: 137, name: "MenuAlt3Icon", icon: MenuAlt3Icon },
  { id: 138, name: "MenuAlt4Icon", icon: MenuAlt4Icon },
  { id: 139, name: "MenuIcon", icon: MenuIcon },
  { id: 140, name: "MicrophoneIcon", icon: MicrophoneIcon },
  { id: 141, name: "MinusCircleIcon", icon: MinusCircleIcon },
  { id: 142, name: "MinusIcon", icon: MinusIcon },
  { id: 143, name: "MinusSmIcon", icon: MinusSmIcon },
  { id: 144, name: "MoonIcon", icon: MoonIcon },
  { id: 145, name: "MusicNoteIcon", icon: MusicNoteIcon },
  { id: 146, name: "NewspaperIcon", icon: NewspaperIcon },
  { id: 147, name: "OfficeBuildingIcon", icon: OfficeBuildingIcon },
  { id: 148, name: "PaperAirplaneIcon", icon: PaperAirplaneIcon },
  { id: 149, name: "PaperClipIcon", icon: PaperClipIcon },
  { id: 150, name: "PauseIcon", icon: PauseIcon },
  { id: 151, name: "PencilAltIcon", icon: PencilAltIcon },
  { id: 152, name: "PencilIcon", icon: PencilIcon },
  { id: 153, name: "PhoneIcon", icon: PhoneIcon },
  { id: 154, name: "PhoneIncomingIcon", icon: PhoneIncomingIcon },
  { id: 155, name: "PhoneMissedCallIcon", icon: PhoneMissedCallIcon },
  { id: 156, name: "PhoneOutgoingIcon", icon: PhoneOutgoingIcon },
  { id: 157, name: "PhotographIcon", icon: PhotographIcon },
  { id: 158, name: "PlayIcon", icon: PlayIcon },
  { id: 159, name: "PlusCircleIcon", icon: PlusCircleIcon },
  { id: 160, name: "PlusIcon", icon: PlusIcon },
  { id: 161, name: "PlusSmIcon", icon: PlusSmIcon },
  { id: 162, name: "PresentationChartBarIcon", icon: PresentationChartBarIcon },
  { id: 163, name: "PresentationChartLineIcon", icon: PresentationChartLineIcon },
  { id: 164, name: "PrinterIcon", icon: PrinterIcon },
  { id: 165, name: "PuzzleIcon", icon: PuzzleIcon },
  { id: 166, name: "QrcodeIcon", icon: QrcodeIcon },
  { id: 167, name: "QuestionMarkCircleIcon", icon: QuestionMarkCircleIcon },
  { id: 168, name: "ReceiptRefundIcon", icon: ReceiptRefundIcon },
  { id: 169, name: "ReceiptTaxIcon", icon: ReceiptTaxIcon },
  { id: 170, name: "RefreshIcon", icon: RefreshIcon },
  { id: 171, name: "ReplyIcon", icon: ReplyIcon },
  { id: 172, name: "RewindIcon", icon: RewindIcon },
{ id: 173, name: "RssIcon", icon: RssIcon },
{ id: 174, name: "SaveAsIcon", icon: SaveAsIcon },
{ id: 175, name: "SaveIcon", icon: SaveIcon },
{ id: 176, name: "ScaleIcon", icon: ScaleIcon },
{ id: 177, name: "ScissorsIcon", icon: ScissorsIcon },
{ id: 178, name: "SearchCircleIcon", icon: SearchCircleIcon },
{ id: 179, name: "SearchIcon", icon: SearchIcon },
{ id: 180, name: "SelectorIcon", icon: SelectorIcon },
{ id: 181, name: "ServerIcon", icon: ServerIcon },
{ id: 182, name: "ShareIcon", icon: ShareIcon },
{ id: 183, name: "ShieldCheckIcon", icon: ShieldCheckIcon },
{ id: 184, name: "ShieldExclamationIcon", icon: ShieldExclamationIcon },
{ id: 185, name: "ShoppingBagIcon", icon: ShoppingBagIcon },
{ id: 186, name: "ShoppingCartIcon", icon: ShoppingCartIcon },
{ id: 187, name: "SortAscendingIcon", icon: SortAscendingIcon },
{ id: 188, name: "SortDescendingIcon", icon: SortDescendingIcon },
{ id: 189, name: "SparklesIcon", icon: SparklesIcon },
{ id: 190, name: "SpeakerphoneIcon", icon: SpeakerphoneIcon },
{ id: 191, name: "StarIcon", icon: StarIcon },
{ id: 192, name: "StatusOfflineIcon", icon: StatusOfflineIcon },
{ id: 193, name: "StatusOnlineIcon", icon: StatusOnlineIcon },
{ id: 194, name: "StopIcon", icon: StopIcon },
{ id: 195, name: "SunIcon", icon: SunIcon },
{ id: 196, name: "SupportIcon", icon: SupportIcon },
{ id: 197, name: "SwitchHorizontalIcon", icon: SwitchHorizontalIcon },
{ id: 198, name: "SwitchVerticalIcon", icon: SwitchVerticalIcon },
{ id: 199, name: "TableIcon", icon: TableIcon },
{ id: 200, name: "TagIcon", icon: TagIcon },
{ id: 201, name: "TemplateIcon", icon: TemplateIcon },
{ id: 202, name: "TerminalIcon", icon: TerminalIcon },
{ id: 203, name: "ThumbDownIcon", icon: ThumbDownIcon },
{ id: 204, name: "ThumbUpIcon", icon: ThumbUpIcon },
{ id: 205, name: "TicketIcon", icon: TicketIcon },
{ id: 206, name: "TranslateIcon", icon: TranslateIcon },
{ id: 207, name: "TrashIcon", icon: TrashIcon },
{ id: 208, name: "TrendingDownIcon", icon: TrendingDownIcon },
{ id: 209, name: "TrendingUpIcon", icon: TrendingUpIcon },
{ id: 210, name: "TruckIcon", icon: TruckIcon },
{ id: 211, name: "UploadIcon", icon: UploadIcon },
{ id: 212, name: "UserAddIcon", icon: UserAddIcon },
{ id: 213, name: "UserCircleIcon", icon: UserCircleIcon },
{ id: 214, name: "UserGroupIcon", icon: UserGroupIcon },
{ id: 215, name: "UserIcon", icon: UserIcon },
{ id: 216, name: "UserRemoveIcon", icon: UserRemoveIcon },
{ id: 217, name: "UsersIcon", icon: UsersIcon },
{ id: 218, name: "VariableIcon", icon: VariableIcon },
{ id: 219, name: "VideoCameraIcon", icon: VideoCameraIcon },
{ id: 220, name: "ViewBoardsIcon", icon: ViewBoardsIcon },
{ id: 221, name: "ViewGridAddIcon", icon: ViewGridAddIcon },
{ id: 222, name: "ViewGridIcon", icon: ViewGridIcon },
{ id: 223, name: "ViewListIcon", icon: ViewListIcon },
{ id: 224, name: "VolumeOffIcon", icon: VolumeOffIcon },
{ id: 225, name: "VolumeUpIcon", icon: VolumeUpIcon },
{ id: 226, name: "WifiIcon", icon: WifiIcon },
{ id: 227, name: "XCircleIcon", icon: XCircleIcon },
{ id: 228, name: "XIcon", icon: XIcon },
{ id: 229, name: "ZoomInIcon", icon: ZoomInIcon },
{ id: 230, name: "ZoomOutIcon", icon: ZoomOutIcon }

];

export default function Header() {
  return (
    <div className="max-w-7xl mx-auto">
      <div className="relative overflow-hidden">
        <main className="pt-16 mx-auto px-4 sm:pt-24 ">
          <div className="text-center">
            <h1 className="text-4xl tracking-tight font-extrabold text-gray-800 sm:text-5xl md:text-6xl">
              <span className="block xl:inline">React</span>{" "}
              <span className="block text-indigo-600 xl:inline">HeroIcons</span>
            </h1>
            <p className="mt-3 mb-8 max-w-md mx-auto text-base text-gray-500 sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">
              Tailwind Outline Heroicons
            </p>
          </div>

          <div className="grid mb-4 grid-cols-8 gap-4">
            {icons.map((icon) => (
              <li
                key={icon.name}
                className="col-span-1 flex flex-col text-center  rounded-lg shadow divide-y divide-gray-200"
              >
                <div className="flex-1 flex flex-col py-6">
                  <icon.icon
                    className="w-8 h-8 mx-auto text-gray-400 "
                    aria-hidden="true"
                  />
                  <h3 className="mt-4 text-gray-900 text-sm font-medium">
                    {icon.name}
                  </h3>
                </div>

                {/* <div>
                  <div className="-mt-px flex divide-x divide-gray-200">
                    <div className="w-0 flex-1 flex">
                      <a
                        href={`mailto:${person.email}`}
                        className="relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-bl-lg hover:text-gray-500"
                      >
                        <MailIcon
                          className="w-5 h-5 text-gray-400"
                          aria-hidden="true"
                        />
                        <span className="ml-3">Email</span>
                      </a>
                    </div>
                    <div className="-ml-px w-0 flex-1 flex">
                      <a
                        href={`tel:${person.telephone}`}
                        className="relative w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-gray-500"
                      >
                        <PhoneIcon
                          className="w-5 h-5 text-gray-400"
                          aria-hidden="true"
                        />
                        <span className="ml-3">Call</span>
                      </a>
                    </div>
                  </div>
                </div> */}
              </li>
            ))}
          </div>
        </main>
      </div>
    </div>
  );
}
